/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the contact form
         * @description Accepts a contact/lead inquiry and forwards it to the Ignitox team by email. Protected by Cloudflare Turnstile (when configured), a honeypot field, per-IP rate limiting and strict validation. Successful submissions return 202 because delivery happens asynchronously from the visitor's perspective.
         */
        post: operations["submitContactForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContactRequest: {
            /** @description Sender's name. */
            name: string;
            /**
             * Format: email
             * @description Reply-to email address.
             */
            email: string;
            /**
             * @description Service of interest. Must stay in sync with the slugs in src/content/services.ts (compile-time checked in src/lib/contact-schema.ts).
             * @enum {string}
             */
            service: "cloud-solutions" | "web-development" | "website-hosting" | "it-consulting" | "general";
            /** @description Project details / inquiry body. */
            message: string;
            /** @description Honeypot — hidden from humans by the UI and must be empty. Submissions with a value are silently discarded. */
            companyWebsite?: string;
            /** @description Cloudflare Turnstile response token. Required whenever Turnstile is configured on the server. */
            turnstileToken?: string;
        };
        ContactAccepted: {
            /** @constant */
            ok: true;
            /** @description Human-readable confirmation shown to the visitor. */
            message: string;
        };
        ApiError: {
            /** @constant */
            ok: false;
            /**
             * @description Machine-readable error category.
             * @enum {string}
             */
            code: "invalid_json" | "validation_error" | "turnstile_failed" | "payload_too_large" | "rate_limited" | "internal_error";
            /** @description Human-readable error shown to the visitor. */
            message: string;
            /** @description Field-level validation problems (validation_error only). */
            issues?: {
                field: string;
                message: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submitContactForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Submission accepted and queued for delivery. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactAccepted"];
                };
            };
            /** @description Malformed JSON or failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Turnstile anti-bot verification failed. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request body exceeds the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limit exceeded for this client. */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected server error (e.g. email delivery failure). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
